version: '3.4'
services:
  netbox:
    image: netboxcommunity/netbox:latest
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=${NETBOX_DB_PASSWORD}
      - REDIS_HOST=redis
      - SECRET_KEY=${NETBOX_SECRET_KEY}
    volumes:
      - ./netbox-media:/opt/netbox/netbox/media

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=netbox
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=${NETBOX_DB_PASSWORD}
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - netbox-redis-data:/data

volumes:
  netbox-postgres-data:
  netbox-redis-data:
