version: '3.5'
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD={{ zabbix_db_password }}
      - POSTGRES_DB=zabbix

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    ports:
      - "8081:8080"
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD={{ zabbix_db_password }}
      - POSTGRES_DB=zabbix
      - PHP_TZ=America/Chicago
      - ZBX_SERVER_NAME=docker-host

  zabbix-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD={{ zabbix_db_password }}
      - POSTGRES_DB=zabbix
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data

volumes:
  zabbix-db-data:
